apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-sc
provisioner: {{ .Values.storage.provisioner }}
parameters:
      {{- if .Values.storage.availabilityDomain }}
      availabilityDomain: {{ .Values.storage.availabilityDomain }}
      {{- end }}
      {{- if .Values.storage.compartmentId }}
      compartmentId: {{ .Values.storage.compartmentId }}
      {{- end }}
      {{- if .Values.storage.volumePerference }}
      volumePerference: {{ .Values.storage.volumePerference }}
      {{- end }}
reclaimPolicy: Retain
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  {{- if .Values.mynamespace }}
  namespace: {{ .Values.mynamespace }}
  {{- else }}
  namespace: default
  {{- end }}
spec:
  storageClassName: {{ .Release.Name }}-sc
  {{- range .Values.storage.accessModes }}
  accessModes:
    - {{ . }}
  {{- end }}  
  resources:
    requests:
      storage: {{ .Values.storage.size }}