apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
    {{- if .Values.mynamespace }}
    namespace: {{ .Values.mynamespace }}
    {{- else }}
    namespace: default
    {{- end }}
type: Opaque
data:
  jenkins_user: {{ .Values.access.admin_user | b64enc | quote }}
  jenkins_password: {{ .Values.access.admin_password | b64enc | quote }}