{{- if .Values.ServiceAccount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-admin-clusterrole
rules:
  - apiGroups: [""]
    resources: 
    {{- range $r := .Values.rbac.resources }}
        - {{ $r | quote }} 
    {{- end }}
    verbs:
    {{- range $v := .Values.rbac.verbs }}
        - {{ $v | quote }} 
    {{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-admin
  {{- if .Values.mynamespace }}
  namespace: {{ .Values.mynamespace }}
  {{- else }}
  namespace: default
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-admin-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-admin-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-admin
  {{- if .Values.mynamespace }}
  namespace: {{ .Values.mynamespace }}
  {{- else }}
  namespace: default
  {{- end }}

{{- end }}