apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  {{- if .Values.mynamespace }}
  namespace: {{ .Values.mynamespace }}
  {{- else }}
  namespace: default
  {{- end }}
spec:
  selector: 
    app: {{ .Release.Name }}-server
  type: {{ .Values.Service.serviceType }}  
  ports:
    - port: {{ .Values.Service.Port }}
      targetPort: {{ .Values.jenkins.targetPort }}
      {{- if eq .Values.Service.serviceType "NodePort" }}
      nodePort: {{ .Values.Service.nodePort }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
      name: {{ .Release.Name }}-agent 
      {{- if .Values.mynamespace }}
      namespace: {{ .Values.mynamespace }}
      {{- else }}
      namespace: default
      {{- end }}
spec:
  ports:
    - port: {{ .Values.jnlp.targetPort }}
      targetPort: {{ .Values.jnlp.targetPort }}
      name: slavelistener
  selector:
    app: {{ .Release.Name }}-server
  type: ClusterIP